### PR TITLE
Change rendering order to prevent visual issues

### PR DESCRIPTION
**Pull request by arothuis**
First of all, thanks for this concise yet effective library.

According to the [SVG spec](svg-spec), subsequent elements are painted on top of previously painted elements.

Because sparkline.js separated the fill and the line (in order to only draw the top outline of the path), it makes sense to draw the fill first and the line later. Otherwise, the fill is shown over the line, causing stroke-width being cut in half and corners looking off.

An example of the visual issues I encountered while working on a dashboard tool:
fnando-sparkline-render-order

I also changed the test script in `package.json`: I needed to this (on Windows)  in order to get the tests working and adapted the snapshots to the new situation. Setting env variables in `package.json` also has been made Windows-compatible.

[svg-spec]: https://www.w3.org/TR/SVG/render.html#RenderingOrder

### CODE REVIEW

**Comment by arothuis** [comment]
As this changes the visual behaviour considerably, if this were to be merged, it justifies a major release.

**Comment by arothuis** [comment]
Interestingly, I am not seeing these issues in the examples (or, for example on the NPM site) -- perhaps because I am styling the svg with a css file besides manually setting the `stroke-width` and `stroke-linejoin`.

I don't think these examples will be affected by this change.

**Comment by fnando** [comment]
Can you create a codepen showing this rendering issue? I'm curious to see it in action.

**Comment by arothuis** [comment]
Thanks for your reply!

Will check if I can reproduce it in a codepen. My usecase is a bit specific (React, external stylesheet), but I'll try and make it as simple as possible.

**Comment by arothuis** [comment]
I reproduced it in a minimal setup on codepen (without React).

The old (v0.3.5) behavior can be found here:
https://codepen.io/anon/pen/VXdKEZ

The currently merged (v0.3.6): 
https://codepen.io/anon/pen/ZxRBOV

The line is twice as thick in the new version because it is no longer cut in half. Not sure, but I think the issue was probably related to customized styling through an external CSS file (including a reset.css). 

*P.S: Even though the API has not changed, the visual behavior might have. In [semver](https://semver.org/), this would constitute a major release (i.e. v1.0.0) or, if one only looks at the API, a minor release (i.e. v0.4.0).*

**Pull request merged**
